### PR TITLE
another try to fix the NTP service in SLE11 distros

### PR DESCRIPTION
**Pull request by tampakrap**
this time by using a map for osrelease

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks good to me but I'll leave this one to @iggy since he's been working on it already.

**Comment by patrickpierson** [comment]
is this also tracking the broken ubuntu ntp load? or just SUSE? 

```
----------
          ID: ntp_running
    Function: service.running
        Name: ntp
      Result: False
     Comment: The following requisites were not found:
                                 watch:
                                     file: /etc/ntp.conf
     Started: 
    Duration: 
     Changes:   
----------
```

**Comment by gravyboat** [comment]
@patrickpierson That was already fixed: https://github.com/saltstack-formulas/ntp-formula/blob/master/ntp/init.sls#L27

**Comment by aboe76** [comment]
@iggy are you able too look at this pr?

**Pull request merged**
